CODE_HOME=$(HOME)/work/cache_sim
BIN=$(CODE_HOME)/bin
OBJECTS=$(CODE_HOME)/objects
SOURCES=$(CODE_HOME)/sources
HEADERS=$(CODE_HOME)/headers
MAKE=/usr/bin/make
GCC=/usr/bin/g++
DEBUG= -g
LINKER_LIBS= -lpthread -lcryptopp
INCLUDES= -I $(CODE_HOME)/headers
GCC_FLAGS= -c -std=c++11

